### ISSUE TITLE
Error when rerouting...

### ISSUE THREAD

**Issue by macik1423** [eopeter/flutter_mapbox_navigation#105]
I have error with simulateRoute: false, when device is out of navigation path, map view all the time is rerouting until I go to path. This is error:

```
E/flutter ( 7321):
E/flutter ( 7321): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FormatException: Unexpected character (at character 49)
E/flutter ( 7321): {  "eventType": "user_off_route",  "data": "{  "latitude": 51.4027233,  "lo...
E/flutter ( 7321):                                                 ^
E/flutter ( 7321):
E/flutter ( 7321): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter ( 7321): #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:934:48)
E/flutter ( 7321): #2      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter ( 7321): #3      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter ( 7321): #4      JsonCodec.decode (dart:convert/json.dart:156:41)
E/flutter ( 7321): #5      MapBoxNavigation._parseRouteEvent
package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart:119
E/flutter ( 7321): #6      MapBoxNavigation._streamRouteEvent.<anonymous closure>
package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart:112
E/flutter ( 7321): #7      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
E/flutter ( 7321): #8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter ( 7321): #9      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 7321): #10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 7321): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 7321): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 7321): #13     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter ( 7321): #14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter ( 7321): #15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter ( 7321): #16     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 7321): #17     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7321): #18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 7321): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 7321): #20     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 7321): #21     _CustomZone.run (dart:async/zone.dart:1093:19)
```

How can I handle this case when rerouting? I wanna show in SnackBar informaction like 'You are out of path' or something similar.

**Comment by eopeter** [comment]
listen for the user_off_route event
