### ISSUE TITLE
 FATAL EXCEPTION: main : Missing required properties: baseUrl user requestUuid

### ISSUE THREAD

**Issue by lexprimost** [eopeter/flutter_mapbox_navigation#128]
Thank u for this package !
when i use    _controller.buildRoute(wayPoints:wayPoints,options: _options);  or when i long press on the map.
i get this error below.
im i doing something wrong ? thanks

```

D/ViewRootImpl@8a36e3c[MainActivity](25614): ViewPostIme pointer 0
D/AndroidRuntime(25614): Shutting down VM
E/AndroidRuntime(25614): FATAL EXCEPTION: main
E/AndroidRuntime(25614): Process: io.takedelivery.takeagent, PID: 25614
E/AndroidRuntime(25614): java.lang.IllegalStateException: Missing required properties: baseUrl user requestUuid
E/AndroidRuntime(25614): 	at com.mapbox.api.directions.v5.models.$AutoValue_RouteOptions$Builder.build($AutoValue_RouteOptions.java:643)
E/AndroidRuntime(25614): 	at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.getRoute(FlutterMapViewFactory.kt:573)
E/AndroidRuntime(25614): 	at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.onMapLongClick(FlutterMapViewFactory.kt:472)
E/AndroidRuntime(25614): 	at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapLongClickListeners(MapGestureDetector.java:1004)
E/AndroidRuntime(25614): 	at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onLongPress(MapGestureDetector.java:402)
E/AndroidRuntime(25614): 	at com.mapbox.android.gestures.StandardGestureDetector$1.onLongPress(StandardGestureDetector.java:45)
E/AndroidRuntime(25614): 	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:929)
E/AndroidRuntime(25614): 	at android.view.GestureDetector.access$300(GestureDetector.java:62)
E/AndroidRuntime(25614): 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:332)
E/AndroidRuntime(25614): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(25614): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(25614): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/AndroidRuntime(25614): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(25614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
I/Process (25614): Sending signal. PID: 25614 SIG: 9
Lost connection to device.

```

**Comment by lexprimost** [comment]
any help ?

**Comment by eopeter** [comment]
I can try to replicate this and get back to you.

**Comment by lexprimost** [comment]
thanks here is a gist : https://gist.github.com/lexprimost/e82a6581f55587975b3844066407c2f6

**Comment by lexprimost** [comment]
any news bro ?

**Comment by aifrosals** [comment]
same issue

**Comment by ShabbirSaifuddin** [comment]
Same Issue here.. does anyone have a solution

**Comment by eopeter** [comment]
this issue is resolved!

**Comment by lexprimost** [comment]
hi, where is the solution ?

**Comment by eopeter** [comment]
Update package to latest or latest code on GitHub master branch

**Comment by syedwarisalirehmani** [comment]
After update to the new version of SDK  com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.0 

the build has failed and shown this error 

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-sdk-gl-core:5.3.0.
   
   I have been using following dependency in the gradle file 
   
 implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-core:3.1.0'
    implementation "com.mapbox.navigation:core:1.5.1"
    implementation "com.mapbox.navigation:ui:1.5.1"
