### ISSUE TITLE
App Crash when restart navigation

### ISSUE THREAD

**Issue by juanmanuelco** [eopeter/flutter_mapbox_navigation#133]
I have implemented navigation in Mapbox.
The first time it works perfect.
The second time the application stays on a black screen and in the console it says "Lost connection to device"

https://user-images.githubusercontent.com/17103810/126841781-7c6e818f-1b66-4d79-9ba8-1a004274f2cd.mp4

**Comment by juanmanuelco** [comment]
@eopeter, Can you check this please ?

**Comment by luis901101** [comment]
I'm having the same problem only on Android... it seems a simple `NullPointerException` here my logcat:

```bash
[  +96 ms] E/AndroidRuntime(27237): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(27237): Process: com.myapp, PID: 27237
[        ] E/AndroidRuntime(27237): java.lang.NullPointerException
[        ] E/AndroidRuntime(27237): 	at com.dormmom.flutter_mapbox_navigation.models.MapBoxRouteProgressEvent.<init>(MapBoxRouteProgressEvent.kt:29)
[        ] E/AndroidRuntime(27237): 	at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onRouteProgressChanged(NavigationActivity.kt:171)
[        ] E/AndroidRuntime(27237): 	at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:549)
[        ] E/AndroidRuntime(27237): 	at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:50)
[        ] E/AndroidRuntime(27237): 	at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:519)
[        ] E/AndroidRuntime(27237): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[        ] E/AndroidRuntime(27237): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[        ] E/AndroidRuntime(27237): 	at android.os.Handler.handleCallback(Handler.java:790)
[        ] E/AndroidRuntime(27237): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/AndroidRuntime(27237): 	at android.os.Looper.loop(Looper.java:164)
[        ] E/AndroidRuntime(27237): 	at android.app.ActivityThread.main(ActivityThread.java:6518)
[        ] E/AndroidRuntime(27237): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(27237): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/AndroidRuntime(27237): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[+68472 ms] Service protocol connection closed.
[        ] Lost connection to device.
```

**Comment by eopeter** [comment]
I can take a look at this tonight.

**Comment by luis901101** [comment]
I think I've found the cause *(at least in my case)*, it has something to do with `simulateRoute: true`, because I set it to false and now app doesn't crash.

**Comment by Imperial-lord** [comment]
This issue needs attention. Sure `simualteRoute: false` fixes it, but that's not a solution.

**Comment by eopeter** [comment]
Stale issue message
