### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ellexaD** [eopeter/flutter_mapbox_navigation#202]
I am writing an app that among the various screens has one that displays a map with markers and another that implements a turn by turn navigator, both using Mapbox. For the first screen I am using the package mapbox_gl v^0.16.0. For the navigator I would like to use flutter_mapbox_navigation 0.0.26.

When I open the screen with the navigator turn by turn on a device with Android 12 the app crashes, on an older device it works correctly.

The error is:
```
`E/MapboxNavNative(19093): User defined HTTP service instance not provided from the module implementation.
E/MapboxNavNative(19093): Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@1e244ba
E/MapboxNavNative(19093): but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@1e244ba
E/MapboxNavNative(19093): Are you calling HttpServiceFactory.setUserDefined() correctly?
E/MapboxModuleProvider(19093): Module loading failed
E/MapboxModuleProvider(19093): java.lang.NoSuchMethodException: com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.<init> []
E/MapboxModuleProvider(19093):  at java.lang.Class.getConstructor0(Class.java:2363)
E/MapboxModuleProvider(19093):  at java.lang.Class.getConstructor(Class.java:1759)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider$noArgConstructorCreator$1.getInstance(MapboxModuleProvider.kt:107)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.fetchRoute(NavigationActivity.kt:107)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onNavigationReady(NavigationActivity.kt:94)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:653)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.access$700(NavigationView.java:75)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView$1.onStyleLoaded(NavigationView.java:247)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.next(MessageQueue.java:339)
E/MapboxModuleProvider(19093):  at android.os.Looper.loopOnce(Looper.java:179)
E/MapboxModuleProvider(19093):  at android.os.Looper.loop(Looper.java:344)
E/MapboxModuleProvider(19093):  at android.app.ActivityThread.main(ActivityThread.java:8184)
E/MapboxModuleProvider(19093):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider(19093):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MapboxModuleProvider(19093):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/MapboxModuleProvider(19093): Module loading failed
E/MapboxModuleProvider(19093): java.lang.NoSuchFieldException: INSTANCE
E/MapboxModuleProvider(19093):  at java.lang.Class.getField(Class.java:1635)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider$kotlinObjectReferenceProvider$1.getInstance(MapboxModuleProvider.kt:117)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.fetchRoute(NavigationActivity.kt:107)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onNavigationReady(NavigationActivity.kt:94)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:653)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.access$700(NavigationView.java:75)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView$1.onStyleLoaded(NavigationView.java:247)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.next(MessageQueue.java:339)
E/MapboxModuleProvider(19093):  at android.os.Looper.loopOnce(Looper.java:179)
E/MapboxModuleProvider(19093):  at android.os.Looper.loop(Looper.java:344)
E/MapboxModuleProvider(19093):  at android.app.ActivityThread.main(ActivityThread.java:8184)
E/MapboxModuleProvider(19093):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider(19093):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MapboxModuleProvider(19093):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/MapboxModuleProvider(19093): Module loading failed
E/MapboxModuleProvider(19093): java.lang.NoSuchMethodException: com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.getInstance []
E/MapboxModuleProvider(19093):  at java.lang.Class.getMethod(Class.java:2103)
E/MapboxModuleProvider(19093):  at java.lang.Class.getMethod(Class.java:1724)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider$singletonReferenceProvider$1.getInstance(MapboxModuleProvider.kt:126)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.fetchRoute(NavigationActivity.kt:107)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onNavigationReady(NavigationActivity.kt:94)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:653)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.access$700(NavigationView.java:75)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView$1.onStyleLoaded(NavigationView.java:247)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.next(MessageQueue.java:339)
E/MapboxModuleProvider(19093):  at android.os.Looper.loopOnce(Looper.java:179)
E/MapboxModuleProvider(19093):  at android.os.Looper.loop(Looper.java:344)
E/MapboxModuleProvider(19093):  at android.app.ActivityThread.main(ActivityThread.java:8184)
E/MapboxModuleProvider(19093):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider(19093):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MapboxModuleProvider(19093):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/MapboxModuleProvider(19093): Module loading failed
E/MapboxModuleProvider(19093): java.lang.reflect.InvocationTargetException
E/MapboxModuleProvider(19093):  at java.lang.reflect.Constructor.newInstance0(Native Method)
E/MapboxModuleProvider(19093):  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider$defaultMapboxModuleCreator$1.getInstance(MapboxModuleProvider.kt:138)
E/MapboxModuleProvider(19093):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.fetchRoute(NavigationActivity.kt:107)
E/MapboxModuleProvider(19093):  at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onNavigationReady(NavigationActivity.kt:94)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:653)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView.access$700(NavigationView.java:75)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.ui.NavigationView$1.onStyleLoaded(NavigationView.java:247)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/MapboxModuleProvider(19093):  at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MapboxModuleProvider(19093):  at android.os.MessageQueue.next(MessageQueue.java:339)
E/MapboxModuleProvider(19093):  at android.os.Looper.loopOnce(Looper.java:179)
E/MapboxModuleProvider(19093):  at android.os.Looper.loop(Looper.java:344)
E/MapboxModuleProvider(19093):  at android.app.ActivityThread.main(ActivityThread.java:8184)
E/MapboxModuleProvider(19093):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider(19093):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MapboxModuleProvider(19093):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/MapboxModuleProvider(19093): Caused by: java.lang.IllegalArgumentException: com.example.provamapnavigatore: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MapboxModuleProvider(19093): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MapboxModuleProvider(19093):  at android.app.PendingIntent.checkFlags(PendingIntent.java:378)
E/MapboxModuleProvider(19093):  at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:461)
E/MapboxModuleProvider(19093):  at android.app.PendingIntent.getActivity(PendingIntent.java:447)
E/MapboxModuleProvider(19093):  at android.app.PendingIntent.getActivity(PendingIntent.java:411)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.createPendingOpenIntent(MapboxTripNotification.kt:275)
E/MapboxModuleProvider(19093):  at com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.<init>(MapboxTripNotification.kt:112)
E/MapboxModuleProvider(19093):  ... 24 more
E/Mbgl-MapChangeReceiver(19093): Exception in onDidFinishLoadingStyle
E/Mbgl-MapChangeReceiver(19093): MapboxInvalidModuleException(type=NavigationTripNotification)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:88)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/Mbgl-MapChangeReceiver(19093):    at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.fetchRoute(NavigationActivity.kt:107)
E/Mbgl-MapChangeReceiver(19093):    at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onNavigationReady(NavigationActivity.kt:94)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:653)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.navigation.ui.NavigationView.access$700(NavigationView.java:75)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.navigation.ui.NavigationView$1.onStyleLoaded(NavigationView.java:247)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/Mbgl-MapChangeReceiver(19093):    at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
E/Mbgl-MapChangeReceiver(19093):    at android.os.MessageQueue.nativePollOnce(Native Method)
E/Mbgl-MapChangeReceiver(19093):    at android.os.MessageQueue.next(MessageQueue.java:339)
E/Mbgl-MapChangeReceiver(19093):    at android.os.Looper.loopOnce(Looper.java:179)
E/Mbgl-MapChangeReceiver(19093):    at android.os.Looper.loop(Looper.java:344)
E/Mbgl-MapChangeReceiver(19093):    at android.app.ActivityThread.main(ActivityThread.java:8184)
E/Mbgl-MapChangeReceiver(19093):    at java.lang.reflect.Method.invoke(Native Method)
E/Mbgl-MapChangeReceiver(19093):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/Mbgl-MapChangeReceiver(19093):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
W/System.err(19093): MapboxInvalidModuleException(type=NavigationTripNotification)
W/System.err(19093):    at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:88)
W/System.err(19093):    at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
W/System.err(19093):    at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
W/System.err(19093):    at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.fetchRoute(NavigationActivity.kt:107)
W/System.err(19093):    at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onNavigationReady(NavigationActivity.kt:94)
W/System.err(19093):    at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:653)
W/System.err(19093):    at com.mapbox.navigation.ui.NavigationView.access$700(NavigationView.java:75)
W/System.err(19093):    at com.mapbox.navigation.ui.NavigationView$1.onStyleLoaded(NavigationView.java:247)
W/System.err(19093):    at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
W/System.err(19093):    at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
W/System.err(19093):    at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
W/System.err(19093):    at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
W/System.err(19093):    at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
W/System.err(19093):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(19093):    at android.os.MessageQueue.next(MessageQueue.java:339)
W/System.err(19093):    at android.os.Looper.loopOnce(Looper.java:179)
W/System.err(19093):    at android.os.Looper.loop(Looper.java:344)
W/System.err(19093):    at android.app.ActivityThread.main(ActivityThread.java:8184)
W/System.err(19093):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19093):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
W/System.err(19093):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
D/Mbgl-HttpRequest(19093): [HTTP] Request with response = 304: Not Modified
D/Mbgl-HttpRequest(19093): [HTTP] This request was cancelled (https://api.mapbox.com/v4/mapbox.mapbox-traffic-v1.json?access_token=SECRETKEY&secure&sku=108ldnacpylbb908cce7b2344ae8ab86ca203847fa7). This is expected for tiles that were being prefetched but are no longer needed for the map to render.
E/libc++abi(19093): terminating with uncaught exception of type jni::PendingJavaException
F/libc    (19093): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 19093 (vamapnavigatore), pid 19093 (vamapnavigatore)
Process name is com.example.provamapnavigatore, not key_process
keyProcess: 0
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'realme/RMX3363EEA/RE54ABL1:12/RKQ1.210503.001/R.GDPR.202212130247:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-02-02 17:02:29.105576346+0100
Process uptime: 0s
Cmdline: com.example.provamapnavigatore
pid: 19093, tid: 19093, name: vamapnavigatore  >>> com.example.provamapnavigatore <<<
uid: 10033
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'terminating with uncaught exception of type jni::PendingJavaException'
    x0  0000000000000000  x1  0000000000004a95  x2  0000000000000006  x3  0000007ffea94d50
    x4  736f646277641f73  x5  736f646277641f73  x6  736f646277641f73  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  47385af5fdec8917  x10 0000000000000000  x11 ffffff80fffffbdf
    x12 0000000000000001  x13 0000009befda83a0  x14 0000737472df7d70  x15 0000000034155555
    x16 000000764e0f0ba8  x17 000000764e0cbc10  x18 000000766845a000  x19 0000000000004a95
    x20 0000000000004a95  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 0000007ffea94fa0
    x24 0000007ffea94e80  x25 0000007ffea94ec0  x26 000000750f789968  x27 000000750f789960
    x28 000000750f789980  x29 0000007ffea94dd0
    lr  000000764e07bf30  sp  0000007ffea94d30  pc  000000764e07bf5c  pst 0000000000001000
backtrace:
      #00 pc 0000000000078f5c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 86c2e03db5ccf75a523a17b3ca80de5c)
      #01 pc 0000000000373aa4  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #02 pc 0000000000373c14  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #03 pc 00000000003711d4  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #04 pc 0000000000370800  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #05 pc 000000000037075c  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (__cxa_throw+112) (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #06 pc 0000000000094680  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #07 pc 00000000000aee88  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #08 pc 0000000000115b8c  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #09 pc 00000000001c3898  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #10 pc 00000000001c3314  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #11 pc 00000000001c5b70  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #12 pc 000000000022177c  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #13 pc 00000000000fb3e0  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #14 pc 000000000021b0c4  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #15 pc 000000000021a930  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #16 pc 000000000021a9fc  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #17 pc 0000000000219c24  /data/app/~~Bej8vKTM1DH6ULr2xnpWXg==/com.example.provamapnavigatore-Gr7wSz-kg2S6ywxOX11rag==/lib/arm64/libmapbox-gl.so (BuildId: 5340fab4c92fd87f8304775de4bc95627e863fd7)
      #18 pc 0000000000018184  /system/lib64/libutils.so (android::Looper::pollInner(int)+916) (BuildId: 6fc8f24a666a9723e0829fb53721b425)
      #19 pc 0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116) (BuildId: 6fc8f24a666a9723e0829fb53721b425)
      #20 pc 0000000000154eb8  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48) (BuildId: 99542d10d69ec22a9f8dcc3dc5fdb59e)
      #21 pc 0000000000334504  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
Lost connection to device.`
```

What can I do to solve it? Thank you

**Comment by eopeter** [comment]
try latest
