### ISSUE TITLE
Version Conflict and Compatibility Issue with MapboxMobileEvents

### ISSUE THREAD

**Issue by Mr94t3z** [eopeter/flutter_mapbox_navigation#320]
I am encountering a version conflict and compatibility issue when I try to run the `example` code (https://github.com/eopeter/flutter_mapbox_navigation/tree/master/example/lib). The error message suggests a conflict with the `MapboxMobileEvents` library among the following dependencies:

- `flutter_mapbox_navigation` (resolved to version 0.2.2), which depends on `MapboxNavigation (~> 2.11)` and ultimately on `MapboxMobileEvents (~> 1.0)`.
- `mapbox_gl` (resolved to version 0.0.1), which depends on `Mapbox-iOS-SDK (~> 6.4.0)` and ultimately on `MapboxMobileEvents (~> 0.10.12)`.

**Full Error Message:**

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                             556ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`:
      (``)
      Using `ARCHS` setting to build architectures of target
      `Pods-RunnerTests`: (``)

    Finding Podfile changes
      A flutter_mapbox_navigation
      - Flutter
      - geocoding_ios
      - geolocator_apple
      - mapbox_gl
      - package_info
      - path_provider_foundation

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_mapbox_navigation` from
    `.symlinks/plugins/flutter_mapbox_navigation/ios`
    -> Fetching podspec for `geocoding_ios` from
    `.symlinks/plugins/geocoding_ios/ios`
    -> Fetching podspec for `geolocator_apple` from
    `.symlinks/plugins/geolocator_apple/ios`
    -> Fetching podspec for `mapbox_gl` from
    `.symlinks/plugins/mapbox_gl/ios`
    -> Fetching podspec for `package_info` from
    `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider_foundation` from
    `.symlinks/plugins/path_provider_foundation/darwin`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_7_3.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/a/7/3/MapboxCoreNavigation/2.17.0/MapboxCoreNavigation.podspec.js
      on exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: all_pods_versions_5_8_b.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.17.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: all_pods_versions_7_7_6.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/7/7/6/MapboxAnnotationExtension/0.0.1-beta.2/MapboxAnnotationExte
      nsion.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_5_9.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/a/5/9/Mapbox-iOS-SDK/6.4.1/Mapbox-iOS-SDK.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/4/2/c/FlutterMacOS/3.13.2/FlutterMacOS.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/7/7/6/MapboxAnnotationExtension/0.0.1-beta.2/MapboxAnnotationExte
      nsion.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path:
      Specs/a/5/9/Mapbox-iOS-SDK/6.4.1/Mapbox-iOS-SDK.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_7_0.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/a/7/0/MapboxMobileEvents/1.0.10/MapboxMobileEvents.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/a/5/9/Mapbox-iOS-SDK/6.4.1/Mapbox-iOS-SDK.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/a/7/0/MapboxMobileEvents/0.10.14/MapboxMobileEvents.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.17.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.16.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.15.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.14.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.13.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.12.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path:
      Specs/5/8/b/MapboxNavigation/2.11.0/MapboxNavigation.podspec.json
      exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: all_pods_versions_8_a_8.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/8/a/8/MapboxMaps/11.0.0-beta.5/MapboxMaps.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_c_6.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/c/c/6/Solar-dev/3.0.1/Solar-dev.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_3_4_a.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/3/4/a/MapboxSpeech/2.1.1/MapboxSpeech.podspec.json exists!
      Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod
    "MapboxMobileEvents":
      In snapshot (Podfile.lock):
        MapboxMobileEvents (= 0.10.14, ~> 0.10.12)

      In Podfile:
        flutter_mapbox_navigation (from
        `.symlinks/plugins/flutter_mapbox_navigation/ios`) was resolved to
        0.2.2, which depends on
          MapboxNavigation (~> 2.11) was resolved to 2.17.0, which depends on
            MapboxMobileEvents (~> 1.0)

        mapbox_gl (from `.symlinks/plugins/mapbox_gl/ios`) was resolved to
        0.0.1, which depends on
          Mapbox-iOS-SDK (~> 6.4.0) was resolved to 6.4.1, which depends on
            MapboxMobileEvents (~> 0.10.12)


    You have either:
     * out-of-date source repos which you can update with `pod repo update`
     or with `pod install --repo-update`.
     * changed the constraints of dependency `MapboxMobileEvents` inside your
     development pod `flutter_mapbox_navigation`.
       You should run `pod update MapboxMobileEvents` to apply changes you've
       made.

    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.
    8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.
    8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.
    8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.
    8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.
    8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.
    8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/installer/analyzer.rb:1082:in `block in
    resolve_dependencies'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/installer.rb:422:in `analyze'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/installer.rb:162:in `install!'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/command/install.rb:52:in `run'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/claide-1.1.0
    /lib/claide/command.rb:334:in `run'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/lib/cocoapods/command.rb:52:in `run'
    /Users/0xgets/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.
    13.0/bin/pod:55:in `<top (required)>'
    /Users/0xgets/.rbenv/versions/3.1.3/bin/pod:25:in `load'
    /Users/0xgets/.rbenv/versions/3.1.3/bin/pod:25:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy
dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 12 Pro Max.
```

**Steps Taken:**

I have attempted to resolve the issue by performing the following steps:

1. Updated CocoaPods specs repository using `pod repo update`.
2. Ran `flutter pub get` to update Flutter dependencies.
3. Executed `pod update MapboxMobileEvents` to update the `MapboxMobileEvents` library.

However, the issue persists, and I am seeking guidance on how to resolve this compatibility problem. 

Any help or suggestions on how to address this issue would be greatly appreciated.

Please let me know if there are specific logs, configuration files, or any additional information needed to diagnose and resolve this issue.

**Comment by Mr94t3z** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 14.0 23A344 darwin-arm64,
    locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by eopeter** [comment]
See #273

**Comment by Mr94t3z** [comment]
there's no solution I can use, I still want to use `mapbox_gl` as a package.

**Comment by eopeter** [comment]
Stale issue message

**Comment by 0x94t3z** [comment]
when you guys fix it?
