### ISSUE TITLE
voiceInstructionsEnabled not working

### ISSUE THREAD

**Issue by luismlg** [eopeter/flutter_mapbox_navigation#342]
Hello, I am using the latest version of the plugin (0.2.2). And it's great. Good job!

Only I'm trying to mute the browser (in multistep), and it doesn't work. Is there a call to mute and unmute along the way?

Thanks for everything

**Comment by eopeter** [comment]
There is no option to mute along the way but it is a great idea

**Comment by tig-bbit** [comment]
I am using the latest verstion of the plugin (0.2.2) also.
And if I do voiceInstructionsEnabled: false, the app is shut down unexpectly.
But the app runs flexible if voiceInstructionsEnable: true.
So I cannot customize voiceInstruction.
How can I resolve this?

E/AndroidRuntime(27278): FATAL EXCEPTION: main
E/AndroidRuntime(27278): Process: com.example.untitled, PID: 27278
E/AndroidRuntime(27278): java.net.MalformedURLException: no protocol: /directions/v5/mapbox/driving/-6.58909461927%2C53.3826809636;-6.587864%2C53.388655;-6.589743%2C53.387647;-6.599891%2C53.389552;-6.599701%2C53.389442;-6.59922%2C53.390455;-6.590373%2C53.382565?access_token=pk.eyJ1IjoibWFjY2EyMDYiLCJhIjoiY2x2YWoydHBxMTc4dTJrbWlrdmdzZm8xbiJ9.KHZzWMOJZUtgrAwBaaoHBg&alternatives=true&avoid_maneuver_radius=18.031&bearings=151.365%2C45%3B%3B%3B%3B%3B%3B&continue_straight=true&enable_refresh=true&geometries=polyline6&layers=0%3B%3B%3B%3B%3B%3B&routes_history=KPXGmPFtKwnbI6HMo6FRbRxdivKvP0ZHiDyopIeIl77o0tgPRT9r1A%3D%3D_us-west-2%2C0%2C0&steps=true&waypoint_names=%3BLyreen%20Lawn%3BLyreen%20Drive%3BMoyglare%20Village%3BMoyglare%20Village%3BMoyglare%20Abbey%3BCross%20Lane&waypoints=0%3B1%3B2%3B3%3B4%3B5%3B6
E/AndroidRuntime(27278): 	at java.net.URL.<init>(URL.java:601)
E/AndroidRuntime(27278): 	at java.net.URL.<init>(URL.java:498)
E/AndroidRuntime(27278): 	at java.net.URL.<init>(URL.java:447)
E/AndroidRuntime(27278): 	at com.mapbox.navigation.base.route.NavigationRouteEx.toNavigationRoute(NavigationRoute.kt:588)
E/AndroidRuntime(27278): 	at com.mapbox.navigation.base.internal.route.NavigationRouteEx.toNavigationRoute(NavigationRouteEx.kt:244)
E/AndroidRuntime(27278): 	at com.mapbox.navigation.base.internal.utils.DirectionsResponseUtilsKt.parseRouteInterface(DirectionsResponseUtils.kt:59)
E/AndroidRuntime(27278): 	at com.mapbox.navigation.base.internal.utils.DirectionsResponseUtilsKt.parseNativeDirectionsAlternative(DirectionsResponseUtils.kt:51)
E/AndroidRuntime(27278): 	at com.mapbox.navigation.core.routealternatives.RouteAlternativesController$processRouteAlternatives$1$alternatives$1$expected$1.invokeSuspend(RouteAlternativesController.kt:219)
E/AndroidRuntime(27278): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(27278): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(27278): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
E/AndroidRuntime(27278): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AndroidRuntime(27278): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
E/AndroidRuntime(27278): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
E/AndroidRuntime(27278): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eec93ae, Dispatchers.Main]
I/Process (27278): Sending signal. PID: 27278 SIG: 9
Lost connection to device.
