### ISSUE TITLE
mapbox_navigation is not working after building the apk

### ISSUE THREAD

**Issue by souhailbakhti** [eopeter/flutter_mapbox_navigation#4]
Hello,

I tried to use your library for my app, everything worked very well in debug, but after releasing the app crashes.

Thank you

**Comment by eopeter** [comment]
Do you have the crash logs?

**Comment by francoisrenier** [comment]
Same issue here. 
Here are the logs : 
2020-06-15 17:15:58.532 25570-25570/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jardiparc, PID: 25570
    java.lang.IllegalAccessError: Method 'java.lang.String c.d.c.a.a()' is inaccessible to class 'c.d.b.a.a.h' (declaration of 'c.d.b.a.a.h' appears in base.apk)
        at c.d.b.a.a.h.c(:78)
        at c.d.b.a.a.h.a(:31)
        at c.d.b.a.a.j.a(:184)
        at h.i.run(:70)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-06-15 17:16:00.059 1404-6490/? E/InputDispatcher: Window handle Window{675675d u0 Application Error: com.example.jardiparc} has no registered input channel
