### ISSUE TITLE
Application crashes when built it.

### ISSUE THREAD

**Issue by jtpdev** [eopeter/flutter_mapbox_navigation#76]
java.lang.IllegalAccessError: Method 'java.lang.String c.e.b.a.a()' is inaccessible to class 'com.mapbox.api.directions.v5.h' (declaration of 'com.mapbox.api.directions.v5.h' appears in /data/app/br.com.alyadus-1/base.apk)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at com.mapbox.api.directions.v5.h.b(:29)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at com.mapbox.api.directions.v5.h.a(:4)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at com.mapbox.api.directions.v5.i.a(:2)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at j.i.run(:3)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-23 14:19:46.960 18985 18985 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-23 14:19:46.970  1643  4118 D InputDispatcher: Focus left window: 18985

I've been having problems that put me in deadlock.

If I build an apk or appbundle as release: **flutter build apk/appbundle --release**, the problem occurs, but If I run as release: **flutter run --release** the problem don't occurs. Then generate the app for all architectures but only for the architecture of the device connected is created the flutter.so. So I can publish in play store, but crash in 64bits architecture.

I tried to force it to generate only 32bits (it will works in 64bits architecture), but for publish in play store my apk was not accepted 'cause it doesn't has generated the 64bits version.

**Comment by jtpdev** [comment]
There was a workarround here: https://github.com/mapbox/mapbox-navigation-android/issues/1857#issuecomment-507743027
