### ISSUE TITLE
Crashing app when mapStyleURL set for MapBoxNavigation

### ISSUE THREAD

**Issue by Dariasz** [eopeter/flutter_mapbox_navigation#87]
I've tried add styled map attribute to MapBoxNavigation in `MapBoxOptions` but I'm still getting this error: 

![Screenshot 2020-10-09 at 23 44 45](https://user-images.githubusercontent.com/19332019/95634248-bcd7f900-0a89-11eb-8294-68b97bb208c7.png)
![Screenshot 2020-10-09 at 23 44 55](https://user-images.githubusercontent.com/19332019/95634261-c2cdda00-0a89-11eb-951c-2d9b2846842d.png)

And my flutter version: 
![Screenshot 2020-10-09 at 23 46 06](https://user-images.githubusercontent.com/19332019/95634320-e85ae380-0a89-11eb-8524-9e185d0c39d6.png)
Android 9 API 28

Do you have any ideas? Thanks a lot

**Comment by eopeter** [comment]
Is the style url public? Does the style url shown below work? 

url: mapbox://styles/eopeter/ckffcmgtl0car1ap80jhp4hsr

**Comment by bossbeagle1509** [comment]
No even with the style you provided above it crashes

**Comment by oiime** [comment]
Can confirm the same error, it seems to happen when a style is changed 

```
E/AndroidRuntime(25410): FATAL EXCEPTION: main
E/AndroidRuntime(25410): Process: com.example.flutter_app1, PID: 25410
E/AndroidRuntime(25410): java.lang.IllegalStateException: Calling addImage when a newer style is loading/has loaded.
E/AndroidRuntime(25410): 	at com.mapbox.mapboxsdk.maps.Style.validateState(Style.java:777)
E/AndroidRuntime(25410): 	at com.mapbox.mapboxsdk.maps.Style.addImage(Style.java:378)
E/AndroidRuntime(25410): 	at com.mapbox.mapboxsdk.maps.Style.addImage(Style.java:319)
E/AndroidRuntime(25410): 	at com.mapbox.mapboxsdk.location.SymbolLocationLayerRenderer.addBitmaps(SymbolLocationLayerRenderer.java:217)
E/AndroidRuntime(25410): 	at com.mapbox.mapboxsdk.location.LocationLayerController.styleBitmaps(LocationLayerController.java:188)
E/AndroidRuntime(25410): 	at com.mapbox.mapboxsdk.location.LocationLayerController.setRenderMode(LocationLayerController.java:115)
E/AndroidRuntime(25410): 	at com.mapbox.mapboxsdk.location.LocationComponent.setRenderMode(LocationComponent.java:676)
E/AndroidRuntime(25410): 	at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.updateLocationLayerRenderMode(NavigationMapboxMap.java:265)
E/AndroidRuntime(25410): 	at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.buildAndStartNavigation(NavigationActivity.kt:274)
E/AndroidRuntime(25410): 	at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.access$buildAndStartNavigation(NavigationActivity.kt:52)
E/AndroidRuntime(25410): 	at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity$fetchRoute$1.onResponse(NavigationActivity.kt:336)
E/AndroidRuntime(25410): 	at com.mapbox.services.android.navigation.v5.internal.navigation.NavigationRouteCallback.onResponse(NavigationRouteCallback.kt:17)
E/AndroidRuntime(25410): 	at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:185)
E/AndroidRuntime(25410): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
E/AndroidRuntime(25410): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(25410): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25410): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(25410): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(25410): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25410): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(25410): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Perhaps related to this?: (https://github.com/mapbox/mapbox-gl-native-android/issues/20)
Though it seems to work differently, it seems to first try to load the default map and then change to the set mapStyleURL midway

Can attempt to reproduce using this edited code of your example (By clicking Start A to B):
Using: minSdkVersion 19 and targetSdkVersion 29, nothing else changed from defaults
```
import 'package:flutter/material.dart';
import 'dart:async';

import 'package:flutter/services.dart';
import 'package:flutter_mapbox_navigation/library.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _platformVersion = 'Unknown';
  String _instruction = "";
  final _origin = WayPoint(
      name: "Way Point 1",
      latitude: 38.9111117447887,
      longitude: -77.04012393951416);
  final _stop1 = WayPoint(
      name: "Way Point 2",
      latitude: 38.91113678979344,
      longitude: -77.03847169876099);
  final _stop2 = WayPoint(
      name: "Way Point 3",
      latitude: 38.91040213277608,
      longitude: -77.03848242759705);
  final _stop3 = WayPoint(
      name: "Way Point 4",
      latitude: 38.909650771013034,
      longitude: -77.03850388526917);
  final _stop4 = WayPoint(
      name: "Way Point 5",
      latitude: 38.90894949285854,
      longitude: -77.03651905059814);
  final _farAway = WayPoint(
      name: "Far Far Away", latitude: 36.1175275, longitude: -115.1839524);

  MapBoxNavigation _directions;
  MapBoxOptions _options;

  bool _arrived = false;
  bool _isMultipleStop = false;
  double _distanceRemaining, _durationRemaining;
  MapBoxNavigationViewController _controller;
  bool _routeBuilt = false;
  bool _isNavigating = false;

  @override
  void initState() {
    super.initState();
    initialize();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initialize() async {
    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    _directions = MapBoxNavigation(onRouteEvent: _onEmbeddedRouteEvent);
    _options = MapBoxOptions(
        initialLatitude: 36.1175275,
        initialLongitude: -115.1839524,
        zoom: 15.0,
        tilt: 0.0,
        bearing: 0.0,
        enableRefresh: false,
        alternatives: true,
        voiceInstructionsEnabled: true,
        bannerInstructionsEnabled: false,
        allowsUTurnAtWayPoints: true,
        mode: MapBoxNavigationMode.walking,
        units: VoiceUnits.metric,
        simulateRoute: true,
        animateBuildRoute: true,
        longPressDestinationEnabled: true,
        language: "en");

    String platformVersion;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      platformVersion = await _directions.platformVersion;
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }

    setState(() {
      _platformVersion = platformVersion;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Column(children: <Widget>[
            Expanded(
              child: SingleChildScrollView(
                child: Column(
                  children: [
                    SizedBox(
                      height: 10,
                    ),
                    Text('Running on: $_platformVersion\n'),
                    Container(
                      color: Colors.grey,
                      width: double.infinity,
                      child: Padding(
                        padding: EdgeInsets.all(10),
                        child: (Text(
                          "Full Screen Navigation",
                          style: TextStyle(color: Colors.white),
                          textAlign: TextAlign.center,
                        )),
                      ),
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        RaisedButton(
                          child: Text("Start A to B"),
                          onPressed: () async {
                            var wayPoints = List<WayPoint>();
                            wayPoints.add(_origin);
                            wayPoints.add(_stop1);

                            await _directions.startNavigation(
                                wayPoints: wayPoints,
                                options: MapBoxOptions(
                                    mode:
                                    MapBoxNavigationMode.walking,
                                    simulateRoute: true,
                                    language: "da",
                                    mapStyleURL: "mapbox://styles/ism01/ckgade1ds0swy19rxmfwhx58r",
                                    units: VoiceUnits.metric));
                          },
                        ),
                        SizedBox(
                          width: 10,
                        ),
                        RaisedButton(
                          child: Text("Start Multi Stop"),
                          onPressed: () async {
                            _isMultipleStop = true;
                            var wayPoints = List<WayPoint>();
                            wayPoints.add(_origin);
                            wayPoints.add(_stop1);
                            wayPoints.add(_stop2);
                            wayPoints.add(_stop3);
                            wayPoints.add(_stop4);
                            wayPoints.add(_origin);

                            await _directions.startNavigation(
                                wayPoints: wayPoints,
                                options: MapBoxOptions(
                                    mode: MapBoxNavigationMode.walking,
                                    simulateRoute: true,
                                    language: "da",
                                    allowsUTurnAtWayPoints: true,
                                    units: VoiceUnits.metric));
                          },
                        )
                      ],
                    ),
                    Container(
                      color: Colors.grey,
                      width: double.infinity,
                      child: Padding(
                        padding: EdgeInsets.all(10),
                        child: (Text(
                          "Embedded Navigation",
                          style: TextStyle(color: Colors.white),
                          textAlign: TextAlign.center,
                        )),
                      ),
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        RaisedButton(
                          child: Text(_routeBuilt && !_isNavigating
                              ? "Clear Route"
                              : "Build Route"),
                          onPressed: _isNavigating
                              ? null
                              : () {
                            if (_routeBuilt) {
                              _controller.clearRoute();
                            } else {
                              var wayPoints = List<WayPoint>();
                              wayPoints.add(_origin);
                              wayPoints.add(_stop1);
                              wayPoints.add(_stop2);
                              wayPoints.add(_stop3);
                              wayPoints.add(_stop4);
                              wayPoints.add(_origin);
                              _isMultipleStop = wayPoints.length > 2;
                              _controller.buildRoute(
                                  wayPoints: wayPoints);
                            }
                          },
                        ),
                        SizedBox(
                          width: 10,
                        ),
                        RaisedButton(
                          child: Text("Start "),
                          onPressed: _routeBuilt && !_isNavigating
                              ? () {
                            _controller.startNavigation();
                          }
                              : null,
                        ),
                        SizedBox(
                          width: 10,
                        ),
                        RaisedButton(
                          child: Text("Cancel "),
                          onPressed: _isNavigating
                              ? () {
                            _controller.finishNavigation();
                          }
                              : null,
                        )
                      ],
                    ),
                    Center(
                      child: Padding(
                        padding: EdgeInsets.all(10),
                        child: Text(
                          "Long-Press Embedded Map to Set Destination",
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                    Container(
                      color: Colors.grey,
                      width: double.infinity,
                      child: Padding(
                        padding: EdgeInsets.all(10),
                        child: (Text(
                          _instruction == null || _instruction.isEmpty
                              ? "Banner Instruction Here"
                              : _instruction,
                          style: TextStyle(color: Colors.white),
                          textAlign: TextAlign.center,
                        )),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.only(
                          left: 20.0, right: 20, top: 20, bottom: 10),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: <Widget>[
                          Row(
                            children: <Widget>[
                              Text("Duration Remaining: "),
                              Text(_durationRemaining != null
                                  ? "${(_durationRemaining / 60).toStringAsFixed(0)} minutes"
                                  : "---")
                            ],
                          ),
                          Row(
                            children: <Widget>[
                              Text("Distance Remaining: "),
                              Text(_distanceRemaining != null
                                  ? "${(_distanceRemaining * 0.000621371).toStringAsFixed(1)} miles"
                                  : "---")
                            ],
                          ),
                        ],
                      ),
                    ),
                    Divider()
                  ],
                ),
              ),
            ),
            Expanded(
              flex: 1,
              child: Container(
                color: Colors.grey,
                child: MapBoxNavigationView(
                    options: _options,
                    onRouteEvent: _onEmbeddedRouteEvent,
                    onCreated:
                        (MapBoxNavigationViewController controller) async {
                      _controller = controller;
                      controller.initialize();
                    }),
              ),
            )
          ]),
        ),
      ),
    );
  }

  Future<void> _onEmbeddedRouteEvent(e) async {
    _distanceRemaining = await _directions.distanceRemaining;
    _durationRemaining = await _directions.durationRemaining;

    switch (e.eventType) {
      case MapBoxEvent.progress_change:
        var progressEvent = e.data as RouteProgressEvent;
        _arrived = progressEvent.arrived;
        if (progressEvent.currentStepInstruction != null)
          _instruction = progressEvent.currentStepInstruction;
        break;
      case MapBoxEvent.route_building:
      case MapBoxEvent.route_built:
        setState(() {
          _routeBuilt = true;
        });
        break;
      case MapBoxEvent.route_build_failed:
        setState(() {
          _routeBuilt = false;
        });
        break;
      case MapBoxEvent.navigation_running:
        setState(() {
          _isNavigating = true;
        });
        break;
      case MapBoxEvent.on_arrival:
        _arrived = true;
        if (!_isMultipleStop) {
          await Future.delayed(Duration(seconds: 3));
          await _controller.finishNavigation();
        } else {}
        break;
      case MapBoxEvent.navigation_finished:
      case MapBoxEvent.navigation_cancelled:
        setState(() {
          _routeBuilt = false;
          _isNavigating = false;
        });
        break;
      default:
        break;
    }
    setState(() {});
  }
}
```
```

**Comment by eopeter** [comment]
This is resolved
