### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected character

### ISSUE THREAD

**Issue by oiime** [eopeter/flutter_mapbox_navigation#94]
It seems that the payload for data within the the event notification is not being escaped (`MapBoxMileStone.toString()`), it happens when I try to change an existing navigation view (which is likely the wrong way of doing it). That is catching `case MapBoxEvent.on_arrival` and attempting to `startNavigation` on an an already started `MapBoxNavigation`
```
E/flutter (16439): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FormatException: Unexpected character (at character 50)
E/flutter (16439): {  "eventType": "milestone_event",  "data": "{  "identifier": "2",  "distan...
E/flutter (16439):                                                  ^
E/flutter (16439): 
E/flutter (16439): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter (16439): #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:934:48)
E/flutter (16439): #2      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter (16439): #3      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter (16439): #4      JsonCodec.decode (dart:convert/json.dart:156:41)
E/flutter (16439): #5      MapBoxNavigation._parseRouteEvent (package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart:119:20)
E/flutter (16439): #6      MapBoxNavigation._streamRouteEvent.<anonymous closure> (package:flutter_mapbox_navigation/flutter_mapbox_navigation
```

**Comment by eopeter** [comment]
this should be working now
